Board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bulletinboard.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bulletinboard/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', PostList.as_view(), name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('post/<int:post_id>', ShowPost.as_view(), name='post'),
    path('post/<int:pk>/update', PostUpdate.as_view(), name='post_edit'),
    path('post/<int:pk>/delete', PostDelete.as_view(), name='post_delete'),
    path('addpost/', AddPost.as_view(), name='add_post'),
    path('post/<int:post_id>/addmessage/', add_message, name='add_message'),
    path('messages/', ShowMessages.as_view(), name='messages'),
    path('messages/<int:message_id>/approve/', approve_message, name='approve_message'),
    path('messages/<int:pk>/delete/', MessageDelete.as_view(), name='message_delete'),
    path('messages/sent', message_sent, name='message_sent'),
    path('category/<slug:cat_slug>/', PostCategory.as_view(), name='category'),
    path('login/', LoginUser.as_view(), name='login'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('verify-code/', VerifyCodeView.as_view(), name='verify_code'),
    path('logout/', logout_user, name='logout'),
]

bulletinboard/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'
        ordering = ['id']


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name='Автор')
    category = models.ForeignKey('Category', models.CASCADE, verbose_name='Категория')
    creation_time = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    title = models.CharField(max_length=255, blank=False, verbose_name='Заголовок')
    body = RichTextUploadingField(verbose_name='Содержание')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post', kwargs={'post_id': self.pk})

    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'
        ordering = ['-creation_time', 'title']


class Message(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Связанный пост')
    author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name='Автор')
    creation_time = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    text = models.TextField(blank=False, verbose_name='Содержание')
    is_approved = models.BooleanField(default=False, verbose_name='Подтверждение')

    def __str__(self):
        return self.text[:20]

    class Meta:
        verbose_name = 'Отклик'
        verbose_name_plural = 'Отклики'
        ordering = ['-creation_time']


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name='Категория')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug})

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['id']


class OneTimeCode(models.Model):
    one_time_code = models.CharField(max_length=10, unique=True, verbose_name='Одноразовый код подтверждения')

    def __str__(self):
        return self.one_time_code

bulletinboard/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError

from .models import *


class AddPostForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].empty_label = 'Категория не выбрана'

    class Meta:
        model = Post
        fields = ['title', 'category', 'body']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 200:
            raise ValidationError('Длина превышает 200 символов')

        return title


class AddMessageForm(forms.ModelForm):
    text = forms.CharField(label='Текст сообщения', widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        model = Message
        fields = ['text']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

bulletinboard/views.py
from django.conf import settings
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import LoginView
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
import string
import secrets

from .filters import MessageFilter
from .forms import *
from .models import *
from .utils import DataMixin

menu = [{'title': 'О сайте', 'url_name': 'about'},
        {'title': 'Обратная связь', 'url_name': 'contact'},
        ]


class PostList(DataMixin, ListView):
    model = Post
    template_name = 'bulletinboard/index.html'
    context_object_name = 'posts'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Главная страница')
        return context | c_def


class PostCategory(DataMixin, ListView):
    model = Post
    template_name = 'bulletinboard/index.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.filter(category__slug=self.kwargs['cat_slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Категория - ' + str(context['posts'][0].category),
                                      cat_selected=context['posts'][0].category_id)
        return context | c_def


class AddPost(LoginRequiredMixin, DataMixin, CreateView):
    form_class = AddPostForm
    model = Post
    template_name = 'bulletinboard/addpost.html'
    success_url = reverse_lazy('home')
    login_url = reverse_lazy('home')
    raise_exception = True

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Создание нового поста')
        return context | c_def

    def form_valid(self, form):
        # Get the Author instance associated with the logged-in user
        author_instance, created = Author.objects.get_or_create(user=self.request.user)

        # Set the author field of the form instance to the Author instance
        form.instance.author = author_instance
        return super().form_valid(form)


class ShowPost(DataMixin, DetailView):
    model = Post
    template_name = 'bulletinboard/post.html'
    context_object_name = 'post'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title=context['post'], form=AddMessageForm())
        return context | c_def

    def get_object(self, queryset=None):
        post_id = self.kwargs.get('post_id')
        return get_object_or_404(Post, id=post_id)


def add_message(request, post_id):
    if request.method == 'POST':
        form = AddMessageForm(request.POST)
        if form.is_valid():
            # Save the comment
            post = Post.objects.get(id=post_id)
            author_instance, created = Author.objects.get_or_create(user=request.user)
            comment = Message(post=post, author=author_instance, text=form.cleaned_data['text'])
            comment.save()
    return redirect('message_sent')


def about(request):
    context = {'title': 'Страница о сайте', 'menu': menu}
    return render(request, template_name='bulletinboard/about.html', context=context)


def contact(request):
    context = {'title': 'Контакты', 'menu': menu}
    return render(request, template_name='bulletinboard/contact.html', context=context)


class ShowMessages(LoginRequiredMixin, DataMixin, ListView):
    model = Message
    template_name = 'bulletinboard/messages.html'
    context_object_name = 'messages'

    def get_queryset(self):
        author_instance, created = Author.objects.get_or_create(user=self.request.user)
        queryset = super().get_queryset()
        self.filterset = MessageFilter(self.request.GET, queryset, user=self.request.user)
        # return Message.objects.filter(post__author_id=author_instance)
        return self.filterset.qs.filter(post__author=author_instance)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Все полученные отклики', filterset=self.filterset)
        return context | c_def


class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'bulletinboard/register.html'
    success_url = reverse_lazy('login')

    def generate_one_time_code(self, length=10):
        alphabet = string.ascii_letters + string.digits
        return ''.join(secrets.choice(alphabet) for _ in range(length))

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация'
        return context

    def form_valid(self, form):
        # Generate a one-time code
        one_time_code = self.generate_one_time_code()

        # Send the one-time code via email
        subject = 'Ваш одноразовый код'
        message = f'Ваш одноразовый код для регистрации: {one_time_code}'
        from_email = settings.DEFAULT_FROM_EMAIL
        recipient_list = [form.cleaned_data['email']]

        send_mail(subject, message, from_email, recipient_list)

        # Save the user, but don't log them in yet
        user = form.save(commit=False)
        user.set_unusable_password()  # Set an unusable password
        user.save()
        self.request.session['register_username'] = user.username
        self.request.session['register_password'] = form.cleaned_data['password1']

        # Store the one-time code in session for validation
        self.request.session['one_time_code'] = one_time_code

        return redirect('verify_code')  # Redirect to the page where the user inputs the code


class VerifyCodeView(View):
    template_name = 'bulletinboard/verify_code.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        entered_code = request.POST.get('one_time_code')
        stored_code = request.session.get('one_time_code')

        if entered_code == stored_code:
            # If the code matches, proceed with user registration
            user = User.objects.get(username=request.session.get('register_username'))
            user.set_password(request.session.get('register_password'))  # Set the actual password
            user.save()

            # Log in the user
            login(request, user)

            # Clear the session data
            del request.session['one_time_code']
            del request.session['register_username']
            del request.session['register_password']

            return redirect('home')

        return render(request, self.template_name, {'error_message': 'Неверный код'})


class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'bulletinboard/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Авторизация'
        return context


def logout_user(request):
    logout(request)
    return redirect('login')


@login_required
def approve_message(request, message_id):
    message = Message.objects.get(pk=message_id)
    message.is_approved = True
    message.save()
    return redirect('messages')


class MessageDelete(LoginRequiredMixin, DataMixin, DeleteView):
    model = Message
    template_name = 'bulletinboard/message_delete.html'
    success_url = reverse_lazy('messages')


def message_sent(request):
    context = {'title': 'Отклик успешно отправлен на подтверждение!', 'menu': menu}
    return render(request, template_name='bulletinboard/message_sent.html', context=context)


class PostUpdate(LoginRequiredMixin, DataMixin, UpdateView):
    form_class = AddPostForm
    model = Post
    template_name = 'bulletinboard/post_edit.html'
    permission_required = ('post.change_post',)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author.user != self.request.user:
            return HttpResponseForbidden("У вас нет доступа к редактированию этого поста.")
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author.user != self.request.user:
            return HttpResponseForbidden("У вас нет доступа к редактированию этого поста.")
        return super().post(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Редактирование поста')
        return context | c_def


class PostDelete(LoginRequiredMixin, DataMixin, DeleteView):
    model = Post
    template_name = 'bulletinboard/post_delete.html'
    success_url = reverse_lazy('home')
    permission_required = ('post.delete_post',)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author.user != self.request.user:
            return HttpResponseForbidden("У вас нет доступа к удалению этого поста.")
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author.user != self.request.user:

bulletinboard/templates/bulletinboard/about.html
{% extends 'bulletinboard/default.html' %}

{% block content %}
<h1>{{title}}</h1>
<p>Содержимое страницы о сайте</p>
{% endblock %}

bulletinboard/templates/bulletinboard/addpost.html
{% extends 'bulletinboard/default.html' %}

{% block content %}
<h1>{{title}}</h1>
<form action="{% url 'add_post' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <button type="submit">Добавить</button>
</form>
{% endblock %}

bulletinboard/templates/bulletinboard/default.html
{% load static %}
{% load bulletinboard_tags %}
<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'bulletinboard/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'bulletinboard/images/main.ico' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
{% block mainmenu %}
		<div class="header">
			<ul id="mainmenu" class="mainmenu">
			<li class="logo"><a href="{% url 'home' %}"><div class="logo"></div></a></li>
			{% for m in menu %}
						<li><a href="{% url m.url_name %}">{{m.title}}</a></li>
			{% endfor %}
				{% if request.user.is_authenticated %}
				<li class="last"> {{user.username}} | <a href="{% url 'logout' %}">Выйти</a></li>
				{% else %}
				<li class="last"><a href="{% url 'register' %}">Регистрация</a> | <a href="{% url 'login' %}">Войти</a></li>
				{% endif %}
			</ul>
			<div class="clear"></div>
		</div>
{% endblock mainmenu %}


<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
<!-- Sidebar слева -->
	<td valign="top" class="left-chapters">
	<ul id="leftchapters">
		{% if cat_selected == 0 %}
		<li class="selected">Все категории</li>
		{% else %}
		<li><a href ="{% url 'home' %}">Все категории</a></li>
		{% endif %}

		{% show_categories cat_selected%}

	</ul>
</td>
<!-- Конец Sidebar'а -->
<td valign="top" class="content">
	<!-- Хлебные крошки -->
	{% block breadcrumbs %}
	{% endblock %}

<!-- Блок контента -->
	<div class="content-text">
{% block content %}
{% endblock %}
	</div>
<!-- Конец блока контента -->

</td></tr></table>
</td></tr>
<!-- Footer -->
<tr><td valign=top>
	<div id="footer">
		<p>&copy; 2023 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажных, строго запрещено.</p>
	</div>
</td></tr></table>
<!-- Конец footer'а и страницы -->
</body>
</html>

bulletinboard/templates/bulletinboard/index.html
{% extends 'bulletinboard/default.html' %}

{% block content %}
<ul class="list-articles">
	{% for p in posts %}
		<li><div class="article-panel">
			<p class="first">Категория: {{p.category}}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Автор: {{p.author}}</p>
			<p class="last">Дата: {{p.creation_time|date:"d-m-Y H:i:s"}}</p>
		</div>
			<h2>{{p.title}}</h2>
				{% autoescape off %}
					{{p.body|truncatewords:20}}
				{% endautoescape %}
			<div class="clear"></div>
			<p class="link-read-post"><a href="{{ p.get_absolute_url }}">Читать пост</a></p>
			</li>
	{% endfor %}
</ul>
{% endblock %}

bulletinboard/templates/bulletinboard/list_categories.html
{% for c in cats %}
    {% if c.pk == cat_selected %}
        <li class="selected">{{c.name}}</li>
    {% else %}
        <li><a href="{{ c.get_absolute_url }}">{{c.name}}</a></li>
    {% endif %}
{% endfor %}

bulletinboard/templates/bulletinboard/login.html
{% extends 'bulletinboard/default.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="post">
    {% csrf_token %}
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit">Войти</button>
</form>
{% endblock %}

bulletinboard/templates/bulletinboard/message_delete.html
{% extends 'bulletinboard/default.html' %}

{% block content %}
<h1>Удаление отклика</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем сообщение "{{ object.text }}"?</p>
    <input type="submit" value="Удалить" />
</form>
{% endblock content %}

bulletinboard/templates/bulletinboard/message_sent.html
{% extends 'bulletinboard/default.html' %}

{% block content %}
Ваше сообщение успешно отправлено на подтверждение автору поста! Оно отобразится на странице поста после подтверждения.
{% endblock content %}

bulletinboard/templates/bulletinboard/messages.html
{% extends 'bulletinboard/index.html' %}

{% block content %}
<h1>Все отклики</h1>
    <form action="" method="get">
        {{ filterset.form.as_p }}
        <input type="submit" value="Найти" />
    </form>
<ul class="list-articles">
	{% for m in messages %}
		<li><div class="article-panel">
			<p class="first">Пост: {{m.post.title|truncatewords:10}}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				Автор: {{m.author}}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				{% if m.is_approved %}
				Статус: Подтверждено!
				{% else %}
				Статус: Ожидает подтверждения...
				{% endif %}
					</p>
			<p class="last">Дата: {{m.creation_time|date:"d-m-Y H:i:s"}}</p>
		</div>
					{{m.text}}
			<div class="clear"></div>
			{% if not m.is_approved %}
			<p class="link-read-post"><a href="{% url 'approve_message' message_id=m.id %}">Подтвердить</a></p>
			{% endif %}
			<p class="link-read-post"><a href="{% url 'message_delete' pk=m.id %}">Удалить</a></p>
			</li>
	{% endfor %}
</ul>
{% endblock %}

bulletinboard/templates/bulletinboard/post.html
{% extends 'bulletinboard/default.html' %}

{% block content %}
<div class="article-panel">
	<p class="first">Категория: {{post.category}}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Автор: {{post.author}}</p>
	<p class="last">Дата: {{post.creation_time|date:"d-m-Y H:i:s"}}</p>
</div>
<h1>{{post.title}}</h1>

{% autoescape off %}
{{post.body}}
{% endautoescape %}
{% if user.is_authenticated and user == post.author.user %}
			<p class="link-read-post"><a href="{% url 'post_edit' pk=post.pk%}">Редактировать пост</a></p>
			<p class="link-read-post"><a href="{% url 'post_delete' pk=post.pk %}">Удалить пост</a></p>
{% endif %}
  <!-- List of comments -->
{% if object.message_set.all %}
  <h3>Отклики</h3>

<ul class="list-articles">
	{% for message in object.message_set.all %}
	{% if message.is_approved %}
		<li><div class="article-panel">
			<p class="first">Автор: {{message.author}}</p>
			<p class="last">Дата: {{message.creation_time|date:"d-m-Y H:i:s"}}</p>
		</div>
            {{message.text}}
			<div class="clear"></div>
			</li>
	{% endif %}
	{% endfor %}
	{% endif %}
</ul>

<!-- Comment form -->
{% if user.is_authenticated %}
<h3>Добавить отклик</h3>
<form action="{% url 'add_message' post_id=post.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить</button>
</form>
{% endif %}

{% endblock %}

bulletinboard/templates/bulletinboard/post_delete.html
{% extends 'bulletinboard/default.html' %}

{% block content %}
<h1>{{title}}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"?</p>
    <input type="submit" value="Удалить" />
</form>
{% endblock content %}

bulletinboard/templates/bulletinboard/post_edit.html
{% extends 'bulletinboard/default.html' %}

{% block content %}
<h1>{{title}}</h1>
<form action="{% url 'post_edit' pk=post.pk %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
{% endblock %}

bulletinboard/templates/bulletinboard/register.html
{% extends 'bulletinboard/default.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="post">
    {% csrf_token %}
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit">Регистрация</button>
</form>
{% endblock %}

bulletinboard/templates/bulletinboard/verify_code.html
{% extends 'bulletinboard/default.html' %}

{% block content %}
<h1>Подтверждение одноразового кода</h1>

    {% if error_message %}
    <p style="color: red;">{{ error_message }}</p>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <label for="one_time_code">Введите одноразовый код:</label>
        <input type="text" id="one_time_code" name="one_time_code" required>
        <button type="submit">Подтвердить код</button>
    </form>
{% endblock %}